
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nofita
 */
public class frame1 extends javax.swing.JFrame 
{
    String temp="";
    Double ti, bt, h1;

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bbideal = new javax.swing.JTextField();
        hasil2 = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jkpr = new javax.swing.JRadioButton();
        jklk = new javax.swing.JRadioButton();
        keluar = new javax.swing.JButton();
        hitung = new javax.swing.JButton();
        cobalagi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        beratbadan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        hasil1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 0, 110, 40);

        jLabel2.setText("Jenis Kelamin");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 180, 80, 20);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 60, 70, 20);

        jLabel4.setText("kg");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 260, 30, 30);

        jLabel5.setText("Berat Badan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 140, 70, 20);

        bbideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbidealActionPerformed(evt);
            }
        });
        getContentPane().add(bbideal);
        bbideal.setBounds(240, 260, 90, 30);

        hasil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasil2ActionPerformed(evt);
            }
        });
        getContentPane().add(hasil2);
        hasil2.setBounds(10, 410, 400, 30);

        tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiActionPerformed(evt);
            }
        });
        getContentPane().add(tinggi);
        tinggi.setBounds(140, 100, 90, 30);

        jLabel6.setText("Tinggi");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 100, 70, 20);

        jLabel7.setText("cm");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 100, 80, 30);

        buttonGroup1.add(jkpr);
        jkpr.setText("Perempuan");
        jkpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkprActionPerformed(evt);
            }
        });
        getContentPane().add(jkpr);
        jkpr.setBounds(140, 180, 110, 23);

        buttonGroup1.add(jklk);
        jklk.setText("Laki-laki");
        getContentPane().add(jklk);
        jklk.setBounds(270, 180, 100, 23);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(270, 220, 90, 30);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(50, 220, 90, 30);

        cobalagi.setText("Coba lagi");
        cobalagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobalagiActionPerformed(evt);
            }
        });
        getContentPane().add(cobalagi);
        cobalagi.setBounds(160, 220, 90, 30);

        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 310, 170, 40);

        beratbadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratbadanActionPerformed(evt);
            }
        });
        getContentPane().add(beratbadan);
        beratbadan.setBounds(140, 140, 90, 30);

        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 140, 80, 30);

        jLabel10.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 260, 170, 40);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(140, 60, 210, 30);

        hasil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasil1ActionPerformed(evt);
            }
        });
        getContentPane().add(hasil1);
        hasil1.setBounds(10, 360, 400, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbidealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbidealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbidealActionPerformed

    private void hasil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasil2ActionPerformed

    private void tinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiActionPerformed

    private void jkprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkprActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
       if(nama.getText().equals("") || tinggi.getText().equals("") || beratbadan.getText().equals(""))
       {
           JOptionPane.showMessageDialog(null, "Data harus diisi");
       }
       
       else if(jkpr.isSelected()|| jklk.isSelected())
       {
           try
           {
               Proses();
           }
           
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(null, "Inputan ada yang belum diisi");
           }
       }
       
       else
       {
           JOptionPane.showMessageDialog(null, "Radio Button harus diisi");
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungActionPerformed

    private void cobalagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobalagiActionPerformed
        nama.setText("");
        tinggi.setText("");
        beratbadan.setText("");
        hasil1.setText("");
        hasil2.setText("");
        bbideal.setText("");
        buttonGroup1.clearSelection();
            // TODO add your handling code here:
    }//GEN-LAST:event_cobalagiActionPerformed

    private void beratbadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratbadanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beratbadanActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void hasil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasil1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bbideal;
    private javax.swing.JTextField beratbadan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cobalagi;
    private javax.swing.JTextField hasil1;
    private javax.swing.JTextField hasil2;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jklk;
    private javax.swing.JRadioButton jkpr;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() 
    {
        ti = Double.valueOf(tinggi.getText());
        bt = Double.valueOf(beratbadan.getText());
        
        if(jkpr.isSelected())
        {
            h1 = (ti - 100) *1;
        }
        
        else if(jklk.isSelected())
        {
            h1 = (ti - 104) * 1;
        }
        
        temp = Double.toString(h1.intValue());
        
        if(h1 < bt)
        {
            bbideal.setText(temp);
            hasil1.setText("Maaf " + nama.getText() + " , Sepertinya anda Overweight :( ");
            hasil2.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
        }
        
        else if(h1 > bt)
        {
            bbideal.setText(temp);
            hasil1.setText("Maaf " + nama.getText() + " , Sepertinya anda Underweight :(");
            hasil2.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        }
        
        else
        {
            bbideal.setText(temp);
            hasil1.setText("Hallo " + nama.getText() + " , Berat badan anda sudah ideal :)");
            hasil2.setText("Lanjutkan pola makan teratur dan gaya hidup sehat :)");
        }
         //To change body of generated methods, choose Tools | Templates.
    }
}
